version: '2'
services:
    jhp2-app:
        image: jhp2
        external_links:
            - jhp2-mysql:mysql
            - jhp2-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhp2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    jhp2-mysql:
        extends:
            file: mysql.yml
            service: jhp2-mysql
    jhp2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhp2-elasticsearch
